version: '3'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gcp_dev:latest
    volumes:
     - ../:/var/www/html
    networks:
     - devnet
    ports:
     - ${APP_PORT}:80
    working_dir: /var/www/html
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: node:latest
    networks:
     - devnet
    volumes:
     - ../:/opt
    working_dir: /opt
    command: echo hi
  
  db:
    image: mariadb:10.2
    volumes:
     - dbdata:/var/lib/mysql
    networks:
     - devnet
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  devnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
